version: '3'
services:
  mysql:
    image: "mysql:5.6"
    container_name: "mysqlserver"
    volumes:
      - ./conf/mysql/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./conf/mysql/backup/:/var/backup
      - ./conf/mysql/data/:/var/lib/mysql
      - ./conf/mysql/shells/backup.sh:/var/backup.sh
      - ./conf/mysql/shells/restore.sh:/var/restore.sh
    environment:
      MYSQL_ROOT_PASSWORD: "741235896"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    networks:
      - dev-network
    restart: always
  influxdb:
    image: "influxdb:1.7-alpine"
    container_name: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - ./conf/influx/data/:/var/lib/influxdb
      - ./conf/influx/backup/:/var/backup
      - ./conf/influx/shells/:/usr/local/bin
    environment:
      TZ: "Asia/Shanghai"
    networks: 
      - dev-network
    restart: always
networks:
  dev-network: 
    driver: bridge