CREATE USER fpm WITH PASSWORD 'Fim741235896';
CREATE USER localdev WITH PASSWORD 'Start123';
CREATE DATABASE fim;
CREATE DATABASE localtest;
GRANT ALL PRIVILEGES ON DATABASE fim TO fpm;
GRANT ALL PRIVILEGES ON DATABASE localtest TO localdev;
